package com.minicard.authorization.domain;

public enum AuthorizationDeclineReason {
    SINGLE_TRANSACTION_LIMIT_EXCEEDED,
    UNSUPPORTED_CURRENCY,
    CARD_NOT_FOUND,
    CARD_BLOCKED,
    CARD_EXPIRED,
    RISK_VELOCITY_EXCEEDED,
    RISK_HIGH_AMOUNT,
    RISK_GEOLOCATION_MISMATCH,
    RISK_BLOCKED_MERCHANT,
    RISK_EXTERNAL_DECLINED,
    RISK_EXTERNAL_UNAVAILABLE,
    CREDIT_ACCOUNT_NOT_FOUND,
    CREDIT_ACCOUNT_BLOCKED,
    CURRENCY_MISMATCH,
    INSUFFICIENT_AVAILABLE_CREDIT
}
