package com.minicard.authorization.domain;

public enum AuthorizationDeclineReason {
    SINGLE_TRANSACTION_LIMIT_EXCEEDED,
    UNSUPPORTED_CURRENCY,
    CARD_NOT_FOUND,
    CARD_BLOCKED,
    CARD_EXPIRED,
    CREDIT_ACCOUNT_NOT_FOUND,
    CREDIT_ACCOUNT_BLOCKED,
    CURRENCY_MISMATCH,
    INSUFFICIENT_AVAILABLE_CREDIT
}
